issue 1 from SmAlex
cyberkost/socialnetwork pull request #21
Opened 2023-07-05 10:40 UTC by SmirnovAlex0891

issue 1

2023-07-05 10:48 UTC, Sergii-Kozhushko requested changes
Записи неслучайные, используй семпл db.posts.aggregate([
    { $sample : { size: 3 } }
])

2023-07-05 11:09 UTC, AnitaWolf approved these changes

2023-07-05 11:12 UTC, Ljur777 approved these changes
good job

2023-07-05 13:10 UTC, cyberkost approved these changes

2023-07-07 07:32 UTC, AnatoliiSidorenco approved these changes

2023-07-10 07:21 UTC, merged